import type { Metadata } from "next";
import { Container } from "@/components/ui/Container";
import { PageHero } from "@/components/sections/PageHero";
import { LegalContent, type LegalSection } from "@/components/sections/LegalContent";
import { buildMetadata } from "@/lib/seo";
import { SITE_CONFIG } from "@/constants/site";

export const metadata: Metadata = buildMetadata({
  title: "Privacy Policy",
  description: `Read ${SITE_CONFIG.name}'s privacy policy to understand how we collect, use, and protect your personal information.`,
  path: "/privacy-policy",
});

const sections: LegalSection[] = [
  {
    heading: "1. Interpretation and Definitions",
    body: [
      "Words with capitalized initial letters have the meanings defined below. These definitions apply whether the terms appear in singular or plural form.",
      {
        definitions: [
          { term: "Account", description: "A unique account created for you to access our Service or parts of it." },
          {
            term: "Affiliate",
            description:
              "An entity that controls, is controlled by, or is under common control with a party, where \"control\" means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote.",
          },
          { term: "Company", description: `Refers to ${SITE_CONFIG.name}, ${SITE_CONFIG.contact.address}.` },
          {
            term: "Cookies",
            description:
              "Small files placed on your device by a website, containing details of your browsing history, used to enhance the Service's functionality.",
          },
          { term: "Country", description: "Refers to India." },
          { term: "Device", description: "Any device that can access the Service, such as a computer, mobile phone, or tablet." },
          { term: "Personal Data", description: "Any information that relates to an identified or identifiable individual." },
          {
            term: "Service",
            description: `Refers to the ${SITE_CONFIG.name} website and our vehicle scrapping and recycling services.`,
          },
          {
            term: "Service Provider",
            description:
              "Any natural or legal person who processes data on behalf of the Company - including third-party companies or individuals employed to facilitate the Service, provide it on our behalf, or assist in analysing how it is used.",
          },
          {
            term: "Usage Data",
            description:
              "Data collected automatically, either generated by use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).",
          },
          {
            term: "You",
            description:
              "The individual accessing or using the Service, or the company or legal entity on whose behalf such individual is accessing or using the Service, as applicable.",
          },
        ],
      },
    ],
  },
  {
    heading: "2. Types of Data We Collect",
    body: [
      "While using our Service, we may ask you to provide certain personally identifiable information that can be used to contact or identify you, including:",
      {
        items: [
          "Full name",
          "Email address",
          "Phone number",
          "Vehicle registration details and documents",
          "Pickup address and location",
        ],
      },
      "We may also automatically collect Usage Data, such as your device's IP address, browser type and version, the pages of our Service you visit, the time and date of your visit, time spent on those pages, and other diagnostic data. When you access the Service through a mobile device, we may also collect information such as the type of mobile device, its unique ID, IP address, operating system, and mobile browser type.",
    ],
  },
  {
    heading: "3. Tracking Technologies and Cookies",
    body: [
      "We use Cookies and similar tracking technologies - such as beacons, tags, and scripts - to monitor activity on our Service, store certain information, and improve and analyse how the Service is used. The Cookies we use include:",
      {
        items: [
          "Essential Cookies: Necessary to provide you with services available through our website and to enable core functionality.",
          "Cookies Acceptance Notice: Identify whether users have accepted the use of cookies on our website.",
          "Functionality Cookies: Remember choices you make, such as your login details or language preference, for a more personalised experience.",
        ],
      },
      "You can instruct your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if you do not accept Cookies, you may not be able to use some parts of our Service.",
    ],
  },
  {
    heading: "4. How We Use Your Personal Data",
    body: [
      "We may use your Personal Data for the following purposes:",
      {
        items: [
          "To provide and maintain our Service, including monitoring how it is used",
          "To process your instant vehicle valuation request and schedule doorstep pickup",
          "To manage your account and registration as a user of the Service",
          "For the performance of a contract, including the purchase and scrapping of your vehicle",
          "To contact you by email, phone, SMS, or WhatsApp with updates, offers, or information related to our services, unless you have opted out of receiving such communications",
          "To manage your requests, including support queries you raise with us",
          "To complete RC cancellation and related documentation on your behalf with regulatory authorities such as RTOs",
          "For business transfers, such as a merger, acquisition, or sale of company assets",
          "For other purposes, including data analysis, identifying usage trends, and improving our Service, products, and marketing",
        ],
      },
    ],
  },
  {
    heading: "5. Sharing of Your Personal Data",
    body: [
      "We may share your personal information in the following situations:",
      {
        items: [
          "With Service Providers, to monitor and analyse the use of our Service or to facilitate payments",
          "With regulatory authorities, including RTOs, as required to complete vehicle deregistration and RC cancellation on your behalf",
          "For business transfers, in connection with any merger, sale of company assets, financing, or acquisition",
          "With Affiliates, in which case we require those affiliates to honour this Privacy Policy",
          "With business partners, to offer you certain products, services, or promotions",
          "With your consent, for any other purpose we disclose when you provide the information",
        ],
      },
      "We do not sell your personal information to third parties.",
    ],
  },
  {
    heading: "6. Retention of Your Data",
    body: [
      "We retain your Personal Data only for as long as necessary for the purposes set out in this Privacy Policy. We retain and use your data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies. Usage Data is generally retained for a shorter period, except where it is used to strengthen the security or functionality of our Service, or where we are legally obligated to retain it for a longer period.",
    ],
  },
  {
    heading: "7. Transfer of Your Data",
    body: [
      "Your information, including Personal Data, may be processed at operating offices and other locations where the parties involved in processing are situated. This means your data may be transferred to, and maintained on, computers located outside your state, province, country, or other governmental jurisdiction, where data protection laws may differ from those of your jurisdiction.",
      "We take all reasonably necessary steps to ensure your data is treated securely and in accordance with this Privacy Policy, and no transfer of your Personal Data takes place without adequate controls in place, including the security of your data and other personal information.",
    ],
  },
  {
    heading: "8. Your Data Protection Rights",
    body: [
      "You have certain rights in relation to your Personal Data. You may:",
      {
        items: [
          "Request access to the personal information we hold about you",
          "Request correction of any inaccurate or incomplete data",
          "Request deletion of your personal data, subject to our legal retention obligations",
          "Withdraw consent for marketing or other communications at any time",
        ],
      },
      `To exercise any of these rights, please contact us at ${SITE_CONFIG.contact.email}.`,
    ],
  },
  {
    heading: "9. Children's Privacy",
    body: [
      "Our Service is not directed to anyone under the age of 18. We do not knowingly collect personally identifiable information from anyone under 18 years of age. If you are a parent or guardian and believe your child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from anyone under 18 without verified parental consent, we take steps to remove that information from our servers.",
    ],
  },
  {
    heading: "10. Security of Your Data",
    body: [
      "The security of your data is important to us. We use commercially acceptable safeguards to protect your Personal Data, including encrypted data transmission and restricted internal access controls. However, no method of transmission over the Internet or method of electronic storage is 100% secure, and we cannot guarantee its absolute security.",
    ],
  },
  {
    heading: "11. Links to Other Websites",
    body: [
      "Our Service may contain links to third-party websites that are not operated by us. If you click on a third-party link, you will be directed to that site. We strongly advise you to review the Privacy Policy of every site you visit, as we have no control over, and assume no responsibility for, the content, privacy policies, or practices of any third-party sites or services.",
    ],
  },
  {
    heading: "12. Changes to This Privacy Policy",
    body: [
      "We may update this Privacy Policy from time to time. We will notify you of any material changes by posting the new Privacy Policy on this page and updating the \"Last updated\" date above. We may also notify you by email and/or through a prominent notice on our Service prior to the change becoming effective.",
      "You are advised to review this Privacy Policy periodically for any changes. Changes take effect when they are posted on this page.",
    ],
  },
  {
    heading: "13. Governing Law",
    body: [
      "This Privacy Policy is governed by the laws of India. Any disputes arising in connection with this policy shall be subject to the exclusive jurisdiction of the courts in New Delhi.",
    ],
  },
  {
    heading: "14. Contact Us",
    body: [
      "If you have any questions about this Privacy Policy, you can contact us:",
      {
        items: [
          `By email: ${SITE_CONFIG.contact.email}`,
          `By phone: ${SITE_CONFIG.contact.phone}`,
          "By visiting our Contact Us page",
        ],
      },
    ],
  },
];

export default function PrivacyPolicyPage() {
  return (
    <>
      <PageHero
        eyebrow="Legal"
        breadcrumb="Privacy Policy"
        title="Privacy Policy"
        description="Last updated: August 27, 2026"
        backgroundImage="/images/banners/privacy.png"
      />
      <section className="bg-surface py-20 sm:py-28">
        <Container className="max-w-3xl">
          <LegalContent sections={sections} />
        </Container>
      </section>
    </>
  );
}
